version: '3'
services:
  app:
    build: .
    command: npx quartz build --output=public/docroot
    volumes:
      - ./quartz.config.ts:/usr/src/app/quartz.config.ts
      - ./quartz.layout.ts:/usr/src/app/quartz.layout.ts
      - ./custom.scss:/usr/src/app/quartz/styles/custom.scss
      - ./content:/usr/src/app/content
      - ./public:/usr/src/app/public
