name: Build site

on:
  push:
    branches:
      - master

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from master branch
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Build site
        run: |
          docker-compose up --build --force-recreate

      - name: Commit to _publish
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public --force
          git commit -m "Result of 'Build site' Action on branch 'master'"
          git push --force origin HEAD:_publish
